export const swedishKeyboard = {
	charToKeyMapping: {
		"§": "§½¶",
		"½": "§½¶",
		"¶": "§½¶",
		1: "1!¡",
		"!": "1!¡",
		"¡": "1!¡",
		2: '2"@',
		'"': '2"@',
		"@": '2"@',
		3: "3#£",
		"#": "3#£",
		"£": "3#£",
		4: "4¤$",
		"¤": "4¤$",
		$: "4¤$",
		5: "5%€",
		"%": "5%€",
		"€": "5%€",
		6: "6&¥",
		"&": "6&¥",
		"¥": "6&¥",
		7: "7/{",
		"/": "7/{",
		"{": "7/{",
		8: "8([",
		"(": "8([",
		"[": "8([",
		9: "9)]",
		")": "9)]",
		"]": "9)]",
		0: "0=}",
		"=": "0=}",
		"}": "0=}",
		"+": "+?\\",
		"?": "+?\\",
		"\\": "+?\\",
		"´": "´`±",
		"`": "´`±",
		"±": "´`±",
		"¨": "¨^~",
		"^": "¨^~",
		"~": "¨^~",
		"'": "'*",
		"*": "'*",
		",": ",;",
		";": ",;",
		".": ".:",
		":": ".:",
		"-": "-_",
		_: "-_",
		"<": "<>|",
		">": "<>|",
		"|": "<>|",
	},

	keysInRow: [14, 13, 14, 12, 4],

	keys: {
		"§½¶": {
			chars: ["§", "½", "¶"],
			finger: "pinkyL",
			keyType: "small",
		},
		"1!¡": {
			chars: ["1", "!¡", "¡"],
			finger: "pinkyL",
			keyType: "small",
		},
		'2"@': {
			chars: ["2", '"', "@"],
			finger: "ringL",
			keyType: "small",
		},
		"3#£": {
			chars: ["3", "#", "£"],
			finger: "middleL",
			keyType: "small",
		},
		"4¤$": {
			chars: ["4", "¤", "$"],
			finger: "indexL",
			keyType: "small",
		},
		"5%€": {
			chars: ["5", "%", "€"],
			finger: "indexL",
			keyType: "small",
		},
		"6&¥": {
			chars: ["6", "&", "¥"],
			finger: "indexR",
			keyType: "small",
		},
		"7/{": {
			chars: ["7", "/", "{"],
			finger: "indexR",
			keyType: "small",
		},
		"8([": {
			chars: ["8", "(", "["],
			finger: "middleR",
			keyType: "small",
		},
		"9)]": {
			chars: ["9", ")", "]"],
			finger: "ringR",
			keyType: "small",
		},
		"0=}": {
			chars: ["0", "=", "}"],
			finger: "pinkyR",
			keyType: "small",
		},
		"+?\\": {
			chars: ["+", "?", "\\"],
			finger: "pinkyR",
			keyType: "small",
		},
		"´`±": {
			chars: ["´", "`", "±"],
			finger: "pinkyR",
			keyType: "small",
		},
		"← Back": {
			chars: ["← Back"],
			finger: "pinkyR",
			keyType: "medium",
			scaler: 1.95,
		},

		"Tab ↹": {
			chars: ["Tab ↹"],
			finger: "pinkyL",
			keyType: "medium",
			scaler: 1.3,
		},
		Q: {
			chars: ["Q"],
			finger: "pinkyL",
			keyType: "small",
		},
		W: {
			chars: ["W"],
			finger: "ringL",
			keyType: "small",
		},
		E: {
			chars: ["E"],
			finger: "middleL",
			keyType: "small",
		},
		R: {
			chars: ["R"],
			finger: "indexL",
			keyType: "small",
		},
		T: {
			chars: ["T"],
			finger: "indexL",
			keyType: "small",
		},
		Y: {
			chars: ["Y"],
			finger: "indexR",
			keyType: "small",
		},
		U: {
			chars: ["U"],
			finger: "indexR",
			keyType: "small",
		},
		I: {
			chars: ["I"],
			finger: "middleR",
			keyType: "small",
		},
		O: {
			chars: ["O"],
			finger: "ringR",
			keyType: "small",
		},
		P: {
			chars: ["P"],
			finger: "pinkyR",
			keyType: "small",
		},
		Å: {
			chars: ["Å"],
			finger: "pinkyR",
			keyType: "small",
		},
		"¨": {
			chars: ["¨", "^", "~"],
			finger: "pinkyR",
			keyType: "small",
		},
		CapsLock: {
			chars: ["CapsLock"],
			finger: "pinkyL",
			keyType: "medium",
			scaler: 1.7,
		},
		A: {
			chars: ["A"],
			finger: "pinkyL",
			keyType: "small",
		},
		S: {
			chars: ["S"],
			finger: "ringL",
			keyType: "small",
		},
		D: {
			chars: ["D"],
			finger: "middleL",
			keyType: "small",
		},
		F: {
			chars: ["F"],
			finger: "indexL",
			keyType: "small",
			marker: "rgb(67, 153, 87)",
		},
		G: {
			chars: ["G"],
			finger: "indexL",
			keyType: "small",
		},
		H: {
			chars: ["H"],
			finger: "indexR",
			keyType: "small",
		},
		J: {
			chars: ["J"],
			finger: "indexR",
			keyType: "small",
			marker: "rgb(191, 82, 82)",
		},
		K: {
			chars: ["K"],
			finger: "middleR",
			keyType: "small",
		},
		L: {
			chars: ["L"],
			finger: "ringR",
			keyType: "small",
		},
		Ö: {
			chars: ["Ö"],
			finger: "pinkyR",
			keyType: "small",
		},
		Ä: {
			chars: ["Ä"],
			finger: "pinkyR",
			keyType: "small",
		},
		"'*": {
			chars: ["'", "*"],
			finger: "pinkyR",
			keyType: "small",
		},
		"↲ Enter": {
			chars: ["↲ Enter"],
			finger: "pinkyR",
			keyType: "medium",
			scaler: 1.28,
		},
		"⇧ Shift": {
			chars: ["⇧ Shift"],
			finger: "pinkyL",
			keyType: "medium",
			scaler: 1.3,
		},
		"<>|": {
			chars: ["<", ">", "|"],
			finger: "pinkyL",
			keyType: "small",
		},
		Z: {
			chars: ["Z"],
			finger: "pinkyL",
			keyType: "small",
		},
		X: {
			chars: ["X"],
			finger: "ringL",
			keyType: "small",
		},
		C: {
			chars: ["C"],
			finger: "middleL",
			keyType: "small",
		},
		V: {
			chars: ["V"],
			finger: "indexL",
			keyType: "small",
		},
		B: {
			chars: ["B"],
			finger: "indexL",
			keyType: "small",
		},
		N: {
			chars: ["N"],
			finger: "indexR",
			keyType: "small",
		},
		M: {
			chars: ["M"],
			finger: "indexR",
			keyType: "small",
		},
		",;": {
			chars: [",", ";"],
			finger: "middleR",
			keyType: "small",
		},
		".:": {
			chars: [".", ":"],
			finger: "ringR",
			keyType: "small",
		},
		"-_": {
			chars: ["-", "_"],
			finger: "pinkyR",
			keyType: "small",
		},
		Ctrl: {
			chars: ["Ctrl"],
			finger: "pinkyL",
			keyType: "medium",
			scaler: 2,
		},
		Alt: {
			chars: ["Alt"],
			finger: "pinkyL",
			keyType: "medium",
			scaler: 2,
		},
		space: {
			chars: ["space"],
			finger: "thumb",
			keyType: "medium",
			scaler: 7,
		},
		"Alt Gr": {
			chars: ["Alt Gr"],
			finger: "ringR",
			keyType: "medium",
			scaler: 2,
		},
	},
};
